name: Increment Version, Build, and Commit

on:
    push:
        branches:
            - main
        paths:
            - 'src/**'
            - '.version'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22'

            - name: Install dependencies
              run: npm install

            - name: Increment version
              run: |
                  # Read the current version from the .version file
                  VERSION=$(cat .version)

                  # Split version into components
                  IFS='.' read -r -a VERSION_COMPONENTS <<< "${VERSION}"
                  MAJOR=${VERSION_COMPONENTS[0]}
                  MINOR=${VERSION_COMPONENTS[1]}
                  PATCH=${VERSION_COMPONENTS[2]}

                  # Increment patch version
                  PATCH=$((PATCH + 1))
                  NEW_VERSION="$MAJOR.$MINOR.$PATCH"

                  # Update the .version file with the new version
                  echo $NEW_VERSION > .version

                  # Update package.json with the new version
                  jq --arg new_version "$NEW_VERSION" '.version = $new_version' package.json > tmp.$$.json && mv tmp.$$.json package.json

            - name: Build project
              run: npx webpack

            - name: Commit changes
              run: |
                  # Commit and push changes
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                  git add .version package.json dist/moneyforwardme.user.js dist/moneyforwardme.meta.js
                  git commit -m "Build and commit from GitHub Actions - Increment version to $NEW_VERSION"
                  git push origin main
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
